---
# Readme: Need to make sure when creating the template, the base OS have VMware Tools installed. Otherwise, the changing of network IP doesn't work.

# On the Ansible server, pre-requisite 
#  yum install python-pyvmomi

# To run playboook without host_key_checking, the command is as follows:
# ansible-playbook -i hosts -e 'host_key_checking=false' test.yml


- name: Create VMware guest
  hosts: all
  connection: local
  gather_facts: False

  tasks:
  - name: Deploy guest from template
    vmware_guest:
      validate_certs: False
      hostname: "{{ vcenter }}"
      username: "{{ user }}"
      password: "{{ pass }}"
#      esxi_hostname: "{{ esxi_hostname }}"
      datacenter: "{{ datacenter }}"
      cluster: "{{ cluster }}"
      name: "{{ vmname }}"
      state: poweredon
      template: "{{ template }}"
      folder: /Test_VM/NTT_Perkeso/rhel_template
      guest_id: "{{ guestid }}"
 #     folder: "{{ folder }}"
      disk:
      - size_gb: "{{ disk }}"
        type: "{{ disktype }}"
        datastore: "{{ datastore }}"
      hardware:
        memory_mb: "{{ memory }}"
        num_cpus: "{{ cpu }}"
        scsi: paravirtual
      networks:
      - name: VM Network
        ip: "{{ vmip }}"
        type: static
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        dns_servers: "{{ dns }}"
        device_type: "{{ devicetype }}"

        
      wait_for_ip_address: yes
    delegate_to: localhost
    registry: deploy
